apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240310102322.0.0+build.6aff574
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240310102322.0.0+build.6aff574
  releaseNotes: |
    Release v20240310102322.0.0+build.6aff574 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-10-03-2024-03-54-27-890275273/where-for-dinner-ui-my-apps-bundle@sha256:395955c886ac3856789ad26293a9f9696b983bf25f47d1f1d1accc4dfeb60ed6
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

