apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240310102155.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240310102155.0.0+build.6aff574
  releaseNotes: |
    Release v20240310102155.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-10-03-2024-03-54-27-890275273/where-for-dinner-my-apps-bundle@sha256:709b796df84083643880ef07003b4e58b501a871c8e9161cfc412c5cd4c883ad
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

