apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20240310102220.0.0+build.6aff574
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20240310102220.0.0+build.6aff574
  releaseNotes: |
    Release v20240310102220.0.0+build.6aff574 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-10-03-2024-03-54-27-890275273/where-for-dinner-search-proc-my-apps-bundle@sha256:e1c46e7fd5eabcc423bba476a08679c0b79a3f11fb3bef888c7c208f6ac6f4eb
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

