apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240310102235.0.0+build.6aff574
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240310102235.0.0+build.6aff574
  releaseNotes: |
    Release v20240310102235.0.0+build.6aff574 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-10-03-2024-03-54-27-890275273/where-for-dinner-notify-my-apps-bundle@sha256:349f2539493bd2a162e0df99c449d547d08a855e59f734908e613c1320297417
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

